const data = [
  {
    userId: 1,
    userImage: '/card-user1.png',
    username: 'lewishamilton',
    description: 'What do you think about this analysis?',
    image: '/markus-winkler.jpg',
    date: '5h',
  },
  {
    userId: 1,
    userImage: '/card-user1.png',
    username: 'lewishamilton',
    description: 'What do you think about this analysis?',
    image: '/markus-winkler.jpg',
    date: '5h',
  },
  {
    userId: 1,
    userImage: '/card-user1.png',
    username: 'lewishamilton',
    description: 'What do you think about this analysis?',
    image: '/markus-winkler.jpg',
    date: '5h',
  },
  {
    userId: 1,
    userImage: '/card-user1.png',
    username: 'lewishamilton',
    description: 'What do you think about this analysis?',
    image: '/markus-winkler.jpg',
    date: '5h',
  },
  {
    userId: 1,
    userImage: '/card-user1.png',
    username: 'lewishamilton',
    description: 'What do you think about this analysis?',
    image: '/markus-winkler.jpg',
    date: '5h',
  },
  {
    userId: 1,
    userImage: '/card-user1.png',
    username: 'lewishamilton',
    description: 'What do you think about this analysis?',
    image: '/markus-winkler.jpg',
    date: '5h',
  },
  {
    userId: 1,
    userImage: '/card-user1.png',
    username: 'lewishamilton',
    description: 'What do you think about this analysis?',
    image: '/markus-winkler.jpg',
    date: '5h',
  },
  {
    userId: 1,
    userImage: '/card-user1.png',
    username: 'lewishamilton',
    description: 'What do you think about this analysis?',
    image: '/markus-winkler.jpg',
    date: '5h',
  },
  {
    userId: 1,
    userImage: '/card-user1.png',
    username: 'lewishamilton',
    description: 'What do you think about this analysis?',
    image: '/markus-winkler.jpg',
    date: '5h',
  },
  {
    userId: 1,
    userImage: '/card-user1.png',
    username: 'lewishamilton',
    description: 'What do you think about this analysis?',
    image: '/markus-winkler.jpg',
    date: '5h',
  },
];

export default data;
